import {
  ExclamationCircleIcon,
  SunIcon,
  MoonIcon,
  ChartPieIcon,
  CalendarIcon,
  FolderOpenIcon,
  BookOpenIcon,
  BriefcaseIcon,
  InboxIcon,
  UserIcon,
  DocumentIcon,
  WalletIcon,
  XMarkIcon,
} from "@heroicons/react/24/solid";

export {
  ExclamationCircleIcon,
  SunIcon,
  MoonIcon,
  ChartPieIcon,
  CalendarIcon,
  FolderOpenIcon,
  BookOpenIcon,
  BriefcaseIcon,
  InboxIcon,
  UserIcon,
  DocumentIcon,
  WalletIcon,
  XMarkIcon,
};
