import {
  ExclamationCircleIcon,
  PlusIcon,
  CheckIcon,
  ArrowTopRightOnSquareIcon,
  PencilSquareIcon,
  TrashIcon,
  SunIcon,
  MoonIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  XMarkIcon,
  EyeSlashIcon,
  BookmarkIcon,
} from "@heroicons/react/20/solid";

export {
  ExclamationCircleIcon,
  PlusIcon,
  CheckIcon,
  ArrowTopRightOnSquareIcon,
  PencilSquareIcon,
  TrashIcon,
  SunIcon,
  MoonIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  XMarkIcon,
  EyeSlashIcon,
  BookmarkIcon,
};
